# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      
      - name: Test with coverage
        run: |
          pytest --runslow --cov=./basicsynbio
        if: ${{ matrix.python-version == 3.8}}

      - name: Upload data to coveralls.io
        run: coveralls
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_SERVICE_NAME: github
        if: ${{ matrix.python-version == 3.8}}

      - name: Test without coverage
        run: |
          pytest --runslow
        if: ${{ matrix.python-version != 3.8}}

  coveralls:
    name: Indicate completion to coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: jpetrucciani/black-check@master
        with:
          path: ./basicsynbio 