name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Test with coverage
      run: |
        pytest --runslow --cov=./basicsynbio
      if: ${{ matrix.python-version == 3.8}}

    - name: Test without coverage
      run: |
        pytest --runslow
      if: ${{ matrix.python-version != 3.8}}

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: rickstaa/action-black@v1
        with:
          black_args: "./basicsynbio --check --diff"

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docsource/"
